services:
  postgres:
    image: postgres:16-alpine
    container_name: minipdm-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: minipdm
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - minipdm_pgdata:/var/lib/postgresql/data

volumes:
  minipdm_pgdata:

